CREATE TABLE IF NOT EXISTS trips (
  id VARCHAR(80) NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  trip_date VARCHAR(120) NOT NULL,
  location VARCHAR(255) NOT NULL,
  image_url TEXT NOT NULL,
  video_url TEXT DEFAULT NULL,
  content LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
